# Config file for an example Majora's Mask: Recompiled mod.

# Fields that end up in the mod's manifest.
[manifest]
# Unique ID of this mod. Pick something long enough that it'll never be the same as any other mod.
# The name displayed in the mod management menu is separate from this so this doesn't need to be human readable.
id = "mnsg_recomp_rando"
# Version of this mod.
version = "1.0.12"
# The name that will show up for this mod in the mod menu. This should be human readable.
display_name = "MNSG Recomp Rando"
# The description that will show up when this mod is displayed in the mod menu. This should be human readable.
description = "MNSG Recomp Rando"
# A short description that will show up in this mod's entry in the mod list. This should be human readable and kept short
# to prevent it from being cut off due to the limited space.
short_description = "MNSG Recomp Rando"
# Authors of this mod.
authors = ["Killklli"]
# ID of the target recomp game.
game_id = "mnsg"
# Minimum version of the target recomp (e.g. Zelda 64: Recompiled) that this mod can run on.
minimum_recomp_version = "0.2.0"
native_libraries = [
  # APCpp Glue:
  { name = "APCpp-Glue", funcs = [
    "rando_init",
    "rando_is_connected",
    "rando_connect_failed",
    "rando_is_scouted",
    "rando_send_location",
    "rando_complete_goal",
    "rando_has_item",
    "rando_has_item_async",
    "rando_location_exists",
    "rando_get_location_has_local_item",
    "rando_get_item_at_location",
    "rando_location_is_checked",
    "rando_location_is_checked_async",
    "rando_get_seed_name",
    "rando_get_own_slot_name",
    "rando_get_death_link_pending",
    "rando_reset_death_link_pending",
    "rando_get_death_link_enabled",
    "rando_send_death_link",
    "rando_get_own_slot_id",
    "rando_get_items_size",
    "rando_get_item",
    "rando_get_item_type",
    "rando_get_location_item_name",
    "rando_get_location_item_player",
    "rando_get_location_type",
    "rando_get_sending_player",
    "rando_get_slotdata_u32",
    "rando_get_datastorage_u32_sync",
    "rando_set_datastorage_u32_sync",
    "rando_set_datastorage_u32_async",
    "rando_get_item_name_from_id",
    "rando_get_sending_player_name",
    "rando_queue_scout",
    "rando_queue_scouts_all",
    "rando_remove_queued_scout",
    "rando_send_queued_scouts",
    "rando_get_saved_apconnect",
    "rando_set_saved_apconnect",
    "rando_access_slotdata_raw_u32_o32",
    "rando_access_slotdata_raw_array_o32",
    "rando_access_slotdata_raw_dict_o32",
    "rando_get_slotdata_raw_o32",
    "rando_iter_slotdata_raw_dict_o32",
    "rando_iter_slotdata_raw_dict_next_o32",
    "rando_access_slotdata_raw_string_o32",
    "rando_access_slotdata_raw_dict_has_member_o32",
    "rando_iter_slotdata_raw_dict_close_o32",
    "rando_get_datastorage_string_sync",
    "rando_set_datastorage_string_async",
  ] },
]

# Inputs to the mod tool.
[inputs]
# Input elf file to generate a mod from.
elf_path = "build/mod.elf"
# Output mod filename.
mod_filename = "mnsg_recomp_rando"
# Reference symbol files.
func_reference_syms_file = "Goemon64RecompSyms/mnsg.us.syms.toml"
data_reference_syms_files = ["Goemon64RecompSyms/mnsg.us.datasyms.toml"]
# Additional files to include in the mod.
additional_files = ["thumb.dds"]
